name: Lint (node)
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
              with:
                  node-version: 22
            - name: Install dependencies
              run: npm ci
            - name: Run lint checks
              run: npm run lint
